# -*- coding: utf-8 -*-
"""Hyunjung_homework_week2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1GFuH8xZ6UhCQlmkpgnqRSt_ZxUZygXQh
"""

## Get eigenvalues
import numpy as np

x = np.linspace(-(np.pi), np.pi, 100)
y = np.linspace(-(np.pi), np.pi, 100)
X, Y = np.meshgrid(x, y)

M_eig_1 = np.zeros((100, 100))
M_eig_2 = np.zeros((100, 100))

for i in range(100):
    for j in range(100):
        xx = X[i, j]
        yy = Y[i, j]
        F = np.exp(yy*1j) + 2.0* np.exp(- 0.5*yy*1j) * np.cos(0.5*np.sqrt(3.0) * xx)
        F_conj = np.exp(- yy*1j) + 2.0* np.exp(0.5*yy*1j) * np.cos(0.5*np.sqrt(3.0) * xx)
        M = np.zeros((2, 2), dtype=complex)
        M[0, 1] += F
        M[1, 0] += F_conj
        M_eigval, _ = np.linalg.eigh(M)
        M_eig_1[i, j] += M_eigval[0]
        M_eig_2[i, j] += M_eigval[1]

## Plot
import matplotlib.pyplot as plt
from matplotlib import cm

fig = plt.figure(figsize=(12,4))
ax1 = fig.add_subplot(121, projection='3d')
ax2 = fig.add_subplot(122, projection='3d')

ax1.plot_surface(X,
                Y, 
                M_eig_1,
                cmap=cm.coolwarm,
                linewidth=0, 
                antialiased=False,
                )
ax1.set_title('Eigenvalue 1')

ax2.plot_surface(X,
                Y, 
                M_eig_2,
                cmap=cm.coolwarm,
                linewidth=0, 
                antialiased=False,
                )
ax2.set_title('Eigenvalue 2')